TRENDLINE_COLOR = "black"
TRENDLINE_WIDTH = 1
SPLINE_WIDTH = 4
SPLINE_COLOR = "black"
MARKER_SIZE = 24
MARKER_SHAPE = "o"
MARKER_COLOR = "black"
ERROR_BAR_COLOR = "black"
HEATMAP_COLOR = "rocket"
FONT_SIZE = 14
plot_type = 3
gridlines = "n"
xbounds = "n"
xmin = 0
xmax = 10
xtickint = 1
xtop = "n"
hidex = "n"
ybounds = "n"
ymin = 0
ymax = 1
ytickint = 0.1
hidey = "n"
xlogscale = "n"
ylogscale = "n"
xlabel = "N"
ylabel = "t"
cbar_label = "Error in S"
cbar_bounds = "y"
cbar_min = 0.0
cbar_max = 1.0
invert_y = "y"
invert_x = "n"
reverse_cmap = "n"
custom_hm_ticks = "y"
x_hm_ticks = 1
y_hm_ticks = 49
legend = "n"
connect_points = "n"
average = "n"
avg_start = -1
avg_end = -1
error_bars = "n"
same_color = "n"
trend = "n"
trend_index = [ 0,]
show_equation = "n"
