#
# !!! USE CONFIG !!! DO NOT EDIT THIS FILE !!!
# THIS FILE IS OVERWRITTEN BY CONFIG ON EACH RUN
# THIS IS JUST TO DECLARE GLOBALS


TRENDLINE_COLOR = 'black'
TRENDLINE_WIDTH = 2
SPLINE_COLOR = 'red'
SPLINE_WIDTH = 2
MARKER_SIZE = 16
MARKER_SHAPE = 'o'
MARKER_COLOR = 'black'
ERROR_BAR_COLOR = 'black'
HEATMAP_COLOR = 'rocket'

plot_type = 1

# Plot formatting
gridlines = 'n'
xbounds = 'n'
xmin = 0
xmax = 10
xtickint = 1
xtop = 'n'
hidex = 'n'
ybounds = 'n'
ymin = 0
ymax = 1
ytickint = 0.1
hidey = 'n'
xlogscale = 'n'
ylogscale = 'n'
xlabel = 'N'
ylabel = '<M>'
cbar_label = 'Error'
cbar_bounds = "n"
cbar_min = 0
cbar_max = 1
invert_y = 'n'
invert_x = 'n'
reverse_cmap = 'n'
custom_hm_ticks = 'n'
x_hm_ticks = 1
y_hm_ticks = 1
legend = 'n'
connect_points = 'n'

# Statistics
average = 'n'
avg_start = -1
avg_end = -1
error_bars = 'n'
same_color = 'n'
trend = 'n'
trend_index = [0]
show_equation = 'n'
